// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"BookTripBotMOBILEHUB","alias":"$LATEST","description":"Bot to make reservations for a visit to a city.","bot-template":"bot-trips","commands-help":["Book a car","Reserve a car","Make a car reservation","Book a hotel","Reserve a room","I want to make a hotel reservation"],"region":"us-east-1"}],
    'aws_cognito_identity_pool_id': 'us-west-2:72242f23-98cf-497b-90d4-fecaf3835427',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'reactchatbot-hosting-mobilehub-362706469',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3jxfb1svpribw.cloudfront.net',
    'aws_mobile_analytics_app_id': 'f0efeb296ab94c858517d1eb5fa1e6cb',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'fab4fbfa-c044-479d-a0bb-4b966a8d8a37',
    'aws_project_name': 'react-chatbot-2019-07-18-11-28-13',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'reactchatbot-mobilehub-362706469',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_Q556Ywxyd',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '58hl692e3bn82m0uf7r81u7j93',
}

export default awsmobile;
